### ISSUE TITLE
Explain how to run this?

### ISSUE THREAD

**Issue by 777paranoia** [maxmmueller/audio-steganography#1]
i went ahead and pasted "pip install wavewhisper" into my terminal and pressed enter. what now? you couldn't have possibly said less about how to use this. assume someone finding this has no idea how python, CLI, binaries, any of that works; please throw the curious folks out there a bone to chew on.

**Comment by maxmmueller** [comment]
Please have a look at the '[usage](https://github.com/maxmmueller/WaveWhisper?tab=readme-ov-file#usage)' section of the readme or the full [documentation](https://github.com/maxmmueller/WaveWhisper/blob/main/docs.md) of the library.
